### PR TITLE
Calculating swap space using swapinfo on FreeBSD

### LINKED ISSUE #54: FreeBSD support for memory widget w/patch
I couldn't get the mem.lua widget to easily work well on FreeBSD with /compat/linux/proc/meminfo via the linprocfs filesystem. The memory stats seemed to be wildly wrong. So I leveraged your sysctl helper and hacked together a mem_freebsd.lua module. It doesn't support buffer memory (since I didn't find source of that data) but otherwise does everything else that mem.lua does.

I couldn't find a nice and easy way to get summary swap information, but meminfo via linprocfs does that, so I just used that.

### PR DESCRIPTION
**Pull request by mutlusun**
Hello,
this pull request will change the memory widget to calculate swap space using `swapinfo` on FreeBSD. This should be last part to close #54.

Are there any comments to code style? Can somebody test the widget again (maybe @psycorama / @dkrand)? Thanks a lot!

### CODE REVIEW

File: widgets/mem_freebsd.lua [hunk 1]
```diff
@@ -47,14 +47,34 @@ local function worker(format)
...
-        _swp.total = vm_swap_total
-        _swp.buf.free = _swp.total - tonumber(vm_stats.v_swapin)
+        -- Initialise variables
+        _swp.usep = 0
+        _swp.inuse = 0
+        _swp.total = 0
+        _swp.buf.free = 0
+
+        -- Read output of swapinfo
+        local f = io.popen("swapinfo")
```
Comment (dkrand) [inline widgets/mem_freebsd.lua]: I'd suggest forcing swapinfo to reporting in KB, just in case the BLOCKSIZE environment variable is set. Add " -k" to the end of the command, making it:  "swapinfo -k"

File: widgets/mem_freebsd.lua [hunk 2]
```diff
@@ -47,14 +47,34 @@ local function worker(format)
...
+        f:close()
+
         -- Rework into megabytes
-        _swp.total = math.floor(_swp.total/1048576)
-        _swp.buf.free = math.floor(_swp.buf.free/1048576)
+        _swp.total = math.floor(_swp.total/1024)
+        _swp.buf.free = math.floor(_swp.buf.free/1024)
         -- Calculate percentage
-        _swp.inuse = _swp.total - _swp.buf.free
         _swp.usep  = math.floor(_swp.inuse / _swp.total * 100)
```
Comment (dkrand) [inline widgets/mem_freebsd.lua]: This is off by a factor of 1024 because _swp.inuse isn't changed to megabytes. Above you need to add:
     _swp.inuse = math.floor(_swp.inuse/1024)
to fix the percentage and to normalize inuse with the other variables.

**Comment by mutlusun** [comment]
Hello,
thanks for your suggestions. I decided to read swapinfo in megabytes, so no further calculation is necessary ...

Best regards

**Comment by mutlusun** [comment]
merging as there are no further comments ...
